# Generated by Django 5.2.12 on 2026-04-07 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_category_task_priority_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='last_decay_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
