# Generated by Django 5.2.12 on 2026-04-07 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pet_last_decay_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='last_decay_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
